spring:
  config:
    location: classpath:application.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: P4ssword
    url: jdbc:mysql://localhost:3306/music_pro_productos
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
api:
  base_url: "api"
  jwt:
    refresh_token_expiration: 10000
server:
  port: 10000
